name: Master

on:
  push:
    branches:
      - master

jobs:
  run-unit-tests:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setups-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.8.6

      - name: Unit Tests
        run: mvn clean package

      - name: Rename the artifact
        run: cp target/bandla-1.0.jar bandla-${{ github.sha }}.jar

      - name: Save the artifact
        uses: actions/upload-artifact@master
        with:
          name:
            name: bandla
            path: bandla-${{ github.sha }}.jar

fake-deploy:
  runs-on: self-hosted
  needs: run-unit-tests
  steps:
    - name: Get the artifact
      uses: actions/download-artifact@master
      with:
        name: bandla

    - name: Fake deploy
      run: ls bandla*.jar